#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug          # change this option for non-debug runs
#SBATCH -N 1              # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00       # adjust the amount of time as necessary
#SBATCH -J auto-serial
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error

rm serial.txt
srun -n 1 -c 1 ./serial -n 500 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 1000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 2000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 4000 -no -s serial.txt
srun -n 1 -c 1 ./serial -n 8000 -no -s serial.txt
./autograder -v serial -s serial.txt
